### ISSUE TITLE
Profanity Check AI Agent

### ISSUE THREAD

**Issue by giosroom99** [CCSU-Computer-Science-Club/CS-Club-Discord-Server-Bots#22]
This agent needs to be re-evaluted as the output sometimes is not accurate. 
We may have to consider finding an alternative solution or train the model (PalmAI api)

@CCSU-Computer-Science-Club/botbuilder

**Comment by Battlekeeper** [comment]
@giosroom99 has this been dealt with yet?

**Comment by giosroom99** [comment]
Yes I used the data u sent me.
